### ISSUE TITLE
Inclusion file

### ISSUE THREAD

**Issue by adelmogentilini** [jolie/docs#112] opened 2024-10-09 06:59 UTC
The notation for the file import should be provided, as it is for StringUtils, for example. In other cases, since it's not specified, you proceed by trial and error.

**Comment by klag** [comment] 2024-10-09 08:19
You mean, before any doc of the standard library?

**Comment by adelmogentilini** [comment] 2024-10-09 09:43
Yes an annotation like in StringUtils 
`[StringUtils](https://docs.jolie-lang.org/v1.13.x-git/language-tools-and-standard-library/standard-library-api/string_utils.html#stringutils)
Inclusion file:

include "string_utils.iol" from string_utils import StringUtils`

**Comment by mwallnoefer** [comment] 2024-12-23 07:32
Duplicate of issue #43 which has been fixed.

**Closed as completed by mwallnoefer** 2024-12-23 07:32 UTC
